import { Team } from './team';

export const WORLD_CUP_2026_TEAMS: Team[] = [
    { id: 'dz', name: 'Algeria', fifaCode: 'ALG' },
    { id: 'ar', name: 'Argentina', fifaCode: 'ARG' },
    { id: 'au', name: 'Australia', fifaCode: 'AUS' },
    { id: 'at', name: 'Austria', fifaCode: 'AUT' },
    { id: 'be', name: 'Belgium', fifaCode: 'BEL' },
    { id: 'ba', name: 'Bosnia and Herzegovina', fifaCode: 'BIH' },
    { id: 'br', name: 'Brazil', fifaCode: 'BRA' },
    { id: 'cm', name: 'Cameroon', fifaCode: 'CMR' },
    { id: 'ca', name: 'Canada', fifaCode: 'CAN' },
    { id: 'cv', name: 'Cabo Verde', fifaCode: 'CPV' },
    { id: 'co', name: 'Colombia', fifaCode: 'COL' },
    { id: 'ci', name: "Côte d'Ivoire", fifaCode: 'CIV' },
    { id: 'hr', name: 'Croatia', fifaCode: 'CRO' },
    { id: 'cw', name: 'Curaçao', fifaCode: 'CUW' },
    { id: 'ec', name: 'Ecuador', fifaCode: 'ECU' },
    { id: 'eg', name: 'Egypt', fifaCode: 'EGY' },
    { id: 'gb-eng', name: 'England', fifaCode: 'ENG' },
    { id: 'fr', name: 'France', fifaCode: 'FRA' },
    { id: 'de', name: 'Germany', fifaCode: 'GER' },
    { id: 'gh', name: 'Ghana', fifaCode: 'GHA' },
    { id: 'ht', name: 'Haiti', fifaCode: 'HAI' },
    { id: 'ir', name: 'Iran', fifaCode: 'IRN' },
    { id: 'iq', name: 'Iraq', fifaCode: 'IRQ' },
    { id: 'jp', name: 'Japan', fifaCode: 'JPN' },
    { id: 'jo', name: 'Jordan', fifaCode: 'JOR' },
    { id: 'kr', name: 'Korea Republic', fifaCode: 'KOR' },
    { id: 'ma', name: 'Morocco', fifaCode: 'MAR' },
    { id: 'mx', name: 'Mexico', fifaCode: 'MEX' },
    { id: 'nl', name: 'Netherlands', fifaCode: 'NED' },
    { id: 'nz', name: 'New Zealand', fifaCode: 'NZL' },
    { id: 'no', name: 'Norway', fifaCode: 'NOR' },
    { id: 'pa', name: 'Panama', fifaCode: 'PAN' },
    { id: 'py', name: 'Paraguay', fifaCode: 'PAR' },
    { id: 'pl', name: 'Poland', fifaCode: 'POL' },
    { id: 'pt', name: 'Portugal', fifaCode: 'POR' },
    { id: 'qa', name: 'Qatar', fifaCode: 'QAT' },
    { id: 'sa', name: 'Saudi Arabia', fifaCode: 'KSA' },
    { id: 'sn', name: 'Senegal', fifaCode: 'SEN' },
    { id: 'gb-sct', name: 'Scotland', fifaCode: 'SCO' },
    { id: 'za', name: 'South Africa', fifaCode: 'RSA' },
    { id: 'es', name: 'Spain', fifaCode: 'ESP' },
    { id: 'se', name: 'Sweden', fifaCode: 'SWE' },
    { id: 'ch', name: 'Switzerland', fifaCode: 'SUI' },
    { id: 'tn', name: 'Tunisia', fifaCode: 'TUN' },
    { id: 'tr', name: 'Türkiye', fifaCode: 'TUR' },
    { id: 'us', name: 'United States', fifaCode: 'USA' },
    { id: 'uy', name: 'Uruguay', fifaCode: 'URU' },
    { id: 'uz', name: 'Uzbekistan', fifaCode: 'UZB' },
];
